name: vigenesia
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.3.3
  font_awesome_flutter: ^10.6.0
  flutter_svg: ^2.0.9
  flutter_lints: ^1.0.0
  flutter_form_builder: ^7.0.1
  another_flushbar: ^1.10.1

flutter:
  uses-material-design: true
